services:

  db:
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    image: postgres:16
    networks:
      - default
    ports:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", $POSTGRES_USER ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  aa:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ./home/architecture_archaeology/boot.sh
    expose:
      - 8000

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    # volumes:
    #   - ./certbot/www:/var/www/certbot/:ro
    #   - ./certbot/conf/:/etc/nginx/ssl/:ro
    restart: always

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw