from .submit_indoorartwork_view import SubmitIndoorArtworkView
from .list_indoorartwork_view import ListIndoorArtworkView
from .detail_indoorartwork_view import DetailIndoorArtworkView
from .submit_frescoe_view import SubmitFrescoeView
