# Generated by Django 5.0 on 2024-03-06 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arch_site', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Элемент постройки',
                'verbose_name_plural': 'Элементы постройки',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('year_min', models.IntegerField(blank=True, null=True, verbose_name='Датировка от:')),
                ('year_max', models.IntegerField(blank=True, help_text='Даты до н.э. должны быть отрицательными', null=True, verbose_name='до:')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('long', models.DecimalField(decimal_places=20, max_digits=23, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=20, max_digits=23, verbose_name='Широта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator+', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='editor+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arch_site.archaeologicalsite', verbose_name='Памятник')),
            ],
            options={
                'verbose_name': 'Постройка',
                'verbose_name_plural': 'Постройки',
            },
        ),
    ]
