# Generated by Django 4.2.7 on 2023-11-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('name', models.CharField(max_length=255)),
                ('long', models.DecimalField(decimal_places=20, max_digits=23)),
                ('lat', models.DecimalField(decimal_places=20, max_digits=23)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
