# Generated by Django 4.2.7 on 2023-12-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('long', models.DecimalField(decimal_places=20, max_digits=23, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=20, max_digits=23, verbose_name='Широта')),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'verbose_name': 'Постройка',
                'verbose_name_plural': 'Постройки',
            },
        ),
    ]
