# Generated by Django 4.2.7 on 2023-11-23 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Постройка', 'verbose_name_plural': 'Постройки'},
        ),
    ]
