# Generated by Django 4.2.7 on 2023-11-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_alter_building_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='date_id',
            new_name='date',
        ),
    ]
