# Generated by Django 4.2.7 on 2023-12-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_remove_comment_building_remove_date_building_and_more'),
        ('building', '0002_building_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpers.comment'),
        ),
        migrations.AddField(
            model_name='building',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpers.date'),
        ),
        migrations.AddField(
            model_name='building',
            name='file',
            field=models.ManyToManyField(to='helpers.file'),
        ),
    ]
