# Generated by Django 5.0 on 2024-04-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_building_preservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ('name', 'id'), 'verbose_name': 'Постройка', 'verbose_name_plural': 'Постройки'},
        ),
    ]
