# Generated by Django 5.0 on 2024-05-04 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0005_delete_archsitefoto'),
        ('building', '0003_alter_building_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arch_site.archaeologicalsite', verbose_name='Памятник'),
        ),
    ]
