# Generated by Django 4.2.7 on 2023-11-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0006_file'),
        ('building', '0003_rename_comment_id_building_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='file',
            field=models.ManyToManyField(to='helpers.file'),
        ),
        migrations.AddField(
            model_name='building',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='helpers.region'),
            preserve_default=False,
        ),
    ]
