# Generated by Django 4.2.7 on 2023-11-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0006_file'),
        ('building', '0004_building_file_building_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='building',
            name='date',
        ),
        migrations.RemoveField(
            model_name='building',
            name='file',
        ),
        migrations.AlterField(
            model_name='building',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpers.region'),
        ),
    ]
