# Generated by Django 4.2.7 on 2023-12-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_comment_building'),
        ('building', '0004_remove_building_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='file',
            field=models.ManyToManyField(null=True, to='helpers.file'),
        ),
    ]
