# Generated by Django 4.2.7 on 2023-11-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_remove_building_comment_remove_building_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='lat',
            field=models.DecimalField(decimal_places=20, max_digits=23, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='building',
            name='long',
            field=models.DecimalField(decimal_places=20, max_digits=23, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
