# Generated by Django 4.2.7 on 2023-12-01 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_alter_building_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='date',
        ),
    ]
