# Generated by Django 4.2.7 on 2023-12-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0006_remove_building_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
