# Generated by Django 4.2.7 on 2023-12-06 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0005_alter_color_description_alter_material_description_and_more'),
        ('building', '0008_alter_building_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='file',
            field=models.ManyToManyField(to='helpers.file'),
        ),
        migrations.AlterField(
            model_name='building',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='helpers.region'),
            preserve_default=False,
        ),
    ]
