# Generated by Django 4.2.7 on 2023-12-07 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0005_alter_color_description_alter_material_description_and_more'),
        ('building', '0009_alter_building_file_alter_building_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='helpers.region'),
        ),
    ]
