# Generated by Django 4.2.7 on 2023-12-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('building', '0010_alter_building_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='file',
            field=models.ManyToManyField(to='file.file'),
        ),
    ]
