# Generated by Django 4.2.7 on 2023-12-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('building', '0011_alter_building_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='file',
            field=models.ManyToManyField(related_name='buildings', to='file.file'),
        ),
    ]
