# Generated by Django 4.2.7 on 2023-12-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0012_alter_building_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='region',
        ),
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
