# Generated by Django 4.2.7 on 2023-12-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0013_remove_building_region_alter_building_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='age_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='age_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='slug',
            field=models.SlugField(),
        ),
    ]
