# Generated by Django 4.2.7 on 2023-12-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0015_building_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='age_max',
            new_name='year_max',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='age_min',
            new_name='year_min',
        ),
        migrations.RemoveField(
            model_name='building',
            name='comment',
        ),
    ]
