# Generated by Django 4.2.7 on 2023-12-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0017_building_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='slug',
        ),
    ]
