# Generated by Django 4.2.7 on 2023-12-12 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0005_alter_archaeologicalsite_slug'),
        ('building', '0019_building_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='file',
        ),
        migrations.AddField(
            model_name='building',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='arch_site.archaeologicalsite'),
            preserve_default=False,
        ),
    ]
