# Generated by Django 5.0 on 2023-12-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0020_remove_building_file_building_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='year_max',
            field=models.IntegerField(verbose_name='До'),
        ),
        migrations.AlterField(
            model_name='building',
            name='year_min',
            field=models.IntegerField(verbose_name='От'),
        ),
        migrations.CreateModel(
            name='BuildingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.building')),
            ],
            options={
                'verbose_name': 'Элемент постройки',
                'verbose_name_plural': 'Элементы постройки',
            },
        ),
    ]
