# Generated by Django 5.0 on 2023-12-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0021_alter_building_comment_alter_building_year_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingpart',
            name='description',
        ),
    ]
