# Generated by Django 5.0 on 2023-12-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0022_remove_buildingpart_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingpart',
            name='building',
        ),
    ]
