# Generated by Django 5.0 on 2023-12-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0025_alter_building_year_max_alter_building_year_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
