# Generated by Django 5.0 on 2024-01-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0014_alter_archaeologicalsite_options'),
        ('building', '0027_alter_building_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='building',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='arch_site.archaeologicalsite', verbose_name='Памятник'),
        ),
        migrations.AlterField(
            model_name='building',
            name='year_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='До:'),
        ),
        migrations.AlterField(
            model_name='building',
            name='year_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Датировка. От:'),
        ),
    ]
