# Generated by Django 5.0 on 2024-02-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0031_building_creator_building_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='building',
            name='editor',
        ),
    ]
