# Generated by Django 5.0 on 2024-02-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0035_alter_building_creator_alter_building_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='year_max',
            field=models.IntegerField(blank=True, help_text='Даты до н.э. должны быть отрицательными', null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='building',
            name='year_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Датировка от:'),
        ),
    ]
