from .building_model_tests import BuildingModelTest
from .display_building_view_tests import DisplayBuildingViewTest
from .create_building_view_tests import CreateBuildingViewTest
from .list_building_view_tests import ListBuildingViewTest
