# Generated by Django 4.2.7 on 2023-11-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('code', models.CharField(max_length=6, verbose_name='16-ный код')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Preservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
