# Generated by Django 5.0 on 2024-03-16 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0001_initial'),
        ('artwork', '0004_alter_frescoe_kind'),
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artefact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact')),
                ('frescoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.frescoe')),
                ('indoor_artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.indoorartwork')),
            ],
        ),
    ]
