# Generated by Django 4.2.7 on 2023-12-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='building',
        ),
        migrations.RemoveField(
            model_name='date',
            name='building',
        ),
        migrations.RemoveField(
            model_name='file',
            name='bulding',
        ),
    ]
