# Generated by Django 4.2.7 on 2023-12-01 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0004_remove_building_comment'),
        ('helpers', '0002_remove_comment_building_remove_date_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='building.building'),
            preserve_default=False,
        ),
    ]
