# Generated by Django 5.0 on 2024-04-01 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_indextable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndexTable',
        ),
    ]
