# Generated by Django 5.0 on 2024-04-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_delete_indextable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=2)),
            ],
        ),
    ]
