# Generated by Django 4.2.7 on 2023-11-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_alter_country_name_alter_region_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
    ]
