# Generated by Django 4.2.7 on 2023-11-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_alter_colors_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('year_min', models.IntegerField()),
                ('year_max', models.IntegerField()),
            ],
        ),
    ]
