# Generated by Django 4.2.7 on 2023-12-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_comment_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pigment',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='preservation',
            name='description',
            field=models.CharField(max_length=100, null=True, verbose_name='Описание'),
        ),
    ]
