# Generated by Django 4.2.7 on 2023-11-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0004_alter_country_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
