# Generated by Django 4.2.7 on 2023-12-01 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0004_alter_color_description_alter_material_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pigment',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preservation',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
