# Generated by Django 5.0 on 2024-04-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0004_element'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ('atomic_number', 'name')},
        ),
    ]
