# Generated by Django 4.2.7 on 2023-12-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0006_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pigment',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='preservation',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
