# Generated by Django 4.2.7 on 2023-11-24 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0005_remove_building_comment_remove_building_date_and_more'),
        ('helpers', '0006_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='building.building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.building'),
        ),
        migrations.AddField(
            model_name='file',
            name='bulding',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='building.building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='helpers.filetype'),
            preserve_default=False,
        ),
    ]
