# Generated by Django 5.0 on 2024-04-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0006_alter_element_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ('name',), 'verbose_name': 'Элемент', 'verbose_name_plural': 'Элементы'},
        ),
    ]
