# Generated by Django 5.0 on 2024-05-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0007_alter_element_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('description', 'id'), 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name', 'id'), 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='filler',
            options={'ordering': ('description', 'id'), 'verbose_name': 'Заполнитель', 'verbose_name_plural': 'Заполнители'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('description', 'id'), 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='mineral',
            options={'ordering': ('description', 'id'), 'verbose_name': 'Минерал', 'verbose_name_plural': 'Минералы'},
        ),
        migrations.AlterModelOptions(
            name='pigment',
            options={'ordering': ('description', 'id'), 'verbose_name': 'Пигмент', 'verbose_name_plural': 'Пигменты'},
        ),
        migrations.AlterModelOptions(
            name='preservation',
            options={'ordering': ('description', 'id'), 'verbose_name': 'Сохранность', 'verbose_name_plural': 'Сохранность'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ('country', 'name'), 'verbose_name': 'Административная принадлежность', 'verbose_name_plural': 'Административная принадлежность'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ('name', 'id'), 'verbose_name': 'Место хранения', 'verbose_name_plural': 'Места хранения'},
        ),
    ]
