# Generated by Django 4.2.7 on 2023-11-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0007_filetype_comment_building_date_building_file_bulding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
