# Generated by Django 4.2.7 on 2023-12-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0002_remove_archaeologicalsite_date_and_more'),
        ('helpers', '0007_alter_color_description_alter_material_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
