# Generated by Django 4.2.7 on 2023-12-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0008_delete_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='building',
        ),
    ]
