# Generated by Django 4.2.7 on 2023-11-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0008_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('F', 'фотография'), ('PIC', 'рисунок'), ('P', 'план')], max_length=100),
        ),
        migrations.DeleteModel(
            name='FileType',
        ),
    ]
