# Generated by Django 4.2.7 on 2023-12-12 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0016_rename_age_max_building_year_max_and_more'),
        ('arch_site', '0003_rename_age_max_archaeologicalsite_year_max_and_more'),
        ('helpers', '0009_remove_comment_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.building'),
        ),
        migrations.AddField(
            model_name='comment',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arch_site.archaeologicalsite'),
        ),
    ]
