# Generated by Django 5.0 on 2023-12-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0012_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pigment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='preservation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
