# Generated by Django 5.0 on 2024-01-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0013_alter_color_description_alter_material_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mineral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('formula', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
