# Generated by Django 5.0 on 2024-01-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0014_mineral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
