# Generated by Django 5.0 on 2024-01-31 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0015_filler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='filler',
            options={'verbose_name': 'Заполнитель', 'verbose_name_plural': 'Заполнители'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='mineral',
            options={'verbose_name': 'Минерал', 'verbose_name_plural': 'Минералы'},
        ),
        migrations.AlterModelOptions(
            name='pigment',
            options={'verbose_name': 'Пигмент', 'verbose_name_plural': 'Пигменты'},
        ),
        migrations.AlterModelOptions(
            name='preservation',
            options={'verbose_name': 'Сохранность', 'verbose_name_plural': 'Сохранность'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Административная принадлежность', 'verbose_name_plural': 'Административная принадлежность'},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Место хранения', 'verbose_name_plural': 'Места хранения'},
        ),
    ]
