# Generated by Django 5.0 on 2024-03-06 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchaeologicalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('year_min', models.IntegerField(blank=True, null=True, verbose_name='Датировка от:')),
                ('year_max', models.IntegerField(blank=True, help_text='Даты до н.э. должны быть отрицательными', null=True, verbose_name='до:')),
                ('name', models.CharField(db_index=True, help_text='Название памятника', max_length=255, verbose_name='Название')),
                ('long', models.DecimalField(decimal_places=20, help_text='Координаты в формате DD.DDDD', max_digits=23, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=20, help_text='Координаты в формате DD.DDDD', max_digits=23, verbose_name='Широта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator+', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='editor+', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(help_text='Выберите один из регионов', on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='helpers.region', verbose_name='Административная принадлежность')),
            ],
            options={
                'verbose_name': 'Памятник',
                'verbose_name_plural': 'Памятники',
                'ordering': ('name',),
            },
        ),
    ]
