# Generated by Django 4.2.7 on 2023-12-12 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('file', '0001_initial'),
        ('helpers', '0007_alter_color_description_alter_material_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchaeologicalSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('long', models.DecimalField(decimal_places=20, max_digits=23, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=20, max_digits=23, verbose_name='Широта')),
                ('slug', models.SlugField(default='')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='helpers.comment')),
                ('date', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpers.date')),
                ('file', models.ManyToManyField(related_name='sites', to='file.file')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='helpers.region')),
            ],
            options={
                'verbose_name': 'Археологический памятник',
                'verbose_name_plural': 'Археологические памятники',
            },
        ),
    ]
