# Generated by Django 4.2.7 on 2023-12-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archaeologicalsite',
            name='date',
        ),
        migrations.AddField(
            model_name='archaeologicalsite',
            name='age_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archaeologicalsite',
            name='age_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
