# Generated by Django 4.2.7 on 2023-12-12 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0002_remove_archaeologicalsite_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archaeologicalsite',
            old_name='age_max',
            new_name='year_max',
        ),
        migrations.RenameField(
            model_name='archaeologicalsite',
            old_name='age_min',
            new_name='year_min',
        ),
        migrations.RemoveField(
            model_name='archaeologicalsite',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='archaeologicalsite',
            name='file',
        ),
    ]
