# Generated by Django 5.0 on 2024-04-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0002_archaeologicalsite_preservation'),
        ('file', '0003_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchSiteFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='file.foto')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='arch_site.archaeologicalsite')),
            ],
        ),
    ]
