# Generated by Django 5.0 on 2024-04-13 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0003_archsitefoto'),
        ('file', '0003_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archsitefoto',
            name='foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.foto'),
        ),
        migrations.AlterField(
            model_name='archsitefoto',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arch_site.archaeologicalsite'),
        ),
    ]
