# Generated by Django 4.2.7 on 2023-12-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0003_rename_age_max_archaeologicalsite_year_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archaeologicalsite',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
