# Generated by Django 5.0 on 2024-04-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0004_alter_archsitefoto_foto_alter_archsitefoto_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchSiteFoto',
        ),
    ]
