# Generated by Django 5.0 on 2023-12-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0005_alter_archaeologicalsite_slug'),
        ('helpers', '0012_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='comment',
            field=models.TextField(null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='lat',
            field=models.DecimalField(decimal_places=20, help_text='Координаты в формате DD.DDDD', max_digits=23, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='long',
            field=models.DecimalField(decimal_places=20, help_text='Координаты в формате DD.DDDD', max_digits=23, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='helpers.region', verbose_name='Административная принадлежность'),
        ),
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='year_max',
            field=models.IntegerField(verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='year_min',
            field=models.IntegerField(verbose_name='Датировка от:'),
        ),
    ]
