# Generated by Django 5.0 on 2023-12-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0006_alter_archaeologicalsite_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='name',
            field=models.CharField(help_text='Название памятника', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='year_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='year_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Датировка от:'),
        ),
    ]
