# Generated by Django 5.0 on 2023-12-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0007_alter_archaeologicalsite_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
