# Generated by Django 5.0 on 2023-12-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0008_alter_archaeologicalsite_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
