# Generated by Django 5.0 on 2024-01-13 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0009_alter_archaeologicalsite_slug'),
        ('helpers', '0014_mineral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archaeologicalsite',
            options={'ordering': ('name',), 'verbose_name': 'Археологический памятник', 'verbose_name_plural': 'Археологические памятники'},
        ),
        migrations.RemoveField(
            model_name='archaeologicalsite',
            name='year_max',
        ),
        migrations.RemoveField(
            model_name='archaeologicalsite',
            name='year_min',
        ),
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='name',
            field=models.CharField(db_index=True, help_text='Название памятника', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='region',
            field=models.ForeignKey(help_text='Выберите один из регионов', on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='helpers.region', verbose_name='Административная принадлежность'),
        ),
    ]
