# Generated by Django 5.0 on 2024-01-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0010_alter_archaeologicalsite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archaeologicalsite',
            name='year_max',
            field=models.DateField(blank=True, null=True, verbose_name='до:'),
        ),
        migrations.AddField(
            model_name='archaeologicalsite',
            name='year_min',
            field=models.DateField(blank=True, null=True, verbose_name='Датировка от:'),
        ),
    ]
