# Generated by Django 5.0 on 2024-01-13 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0011_archaeologicalsite_year_max_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archaeologicalsite',
            name='year_max',
        ),
        migrations.RemoveField(
            model_name='archaeologicalsite',
            name='year_min',
        ),
    ]
