# Generated by Django 5.0 on 2024-01-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0012_remove_archaeologicalsite_year_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archaeologicalsite',
            name='year_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='до:'),
        ),
        migrations.AddField(
            model_name='archaeologicalsite',
            name='year_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Датировка от:'),
        ),
    ]
