# Generated by Django 5.0 on 2024-01-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0013_archaeologicalsite_year_max_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archaeologicalsite',
            options={'ordering': ('name',), 'verbose_name': 'Памятник', 'verbose_name_plural': 'Памятники'},
        ),
    ]
