# Generated by Django 5.0 on 2024-02-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0021_alter_archaeologicalsite_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archaeologicalsite',
            name='year_max',
            field=models.IntegerField(blank=True, help_text='Даты до н.э. должны быть отрицательными', null=True, verbose_name='до:'),
        ),
    ]
