# Generated by Django 5.0 on 2024-01-05 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arch_site', '0009_alter_archaeologicalsite_slug'),
        ('helpers', '0013_alter_color_description_alter_material_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=100, verbose_name='Шифр')),
                ('year_min', models.IntegerField(verbose_name='Датировка от:')),
                ('year_max', models.IntegerField(verbose_name='до:')),
                ('find_date_from', models.IntegerField(null=True, verbose_name='Год находки от:')),
                ('find_date_to', models.IntegerField(null=True, verbose_name='до:')),
                ('comment', models.TextField(null=True, verbose_name='Примечание')),
                ('square_number', models.CharField(max_length=255, null=True, verbose_name='Номер квадрата/участка/пласта по археологическим отчетам')),
                ('museum_code', models.CharField(max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arch_site.archaeologicalsite', verbose_name='Постройка')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpers.storage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
