# Generated by Django 5.0 on 2024-01-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artefact',
            options={'verbose_name': 'Находка', 'verbose_name_plural': 'Находки'},
        ),
    ]
