# Generated by Django 5.0 on 2024-03-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='code',
            field=models.IntegerField(db_index=True, null=True, unique=True, verbose_name='Шифр'),
        ),
    ]
