# Generated by Django 5.0 on 2024-01-18 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0002_alter_artefact_options'),
        ('helpers', '0014_mineral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='museum_code',
            field=models.CharField(max_length=255, verbose_name='Музейный шифр'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpers.storage', verbose_name='Место хранения'),
        ),
    ]
