# Generated by Django 5.0 on 2024-04-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0002_alter_artefact_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='museum_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Музейный шифр'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='square_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер квадрата/участка/пласта по археологическим отчетам'),
        ),
    ]
