# Generated by Django 5.0 on 2024-01-31 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0014_alter_archaeologicalsite_options'),
        ('artefact', '0003_alter_artefact_museum_code_alter_artefact_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='find_date_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год находки от:'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='find_date_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='arch_site.archaeologicalsite', verbose_name='Памятник'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='year_max',
            field=models.IntegerField(blank=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='year_min',
            field=models.IntegerField(blank=True, verbose_name='Датировка от:'),
        ),
    ]
