# Generated by Django 5.0 on 2024-04-10 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0004_alter_artefact_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artefact',
            options={'ordering': ('code', 'id'), 'verbose_name': 'Находка', 'verbose_name_plural': 'Находки'},
        ),
    ]
