# Generated by Django 5.0 on 2024-04-19 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0005_alter_artefact_options'),
        ('building', '0003_alter_building_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.building', verbose_name='Постройка'),
        ),
        migrations.AddField(
            model_name='artefact',
            name='building_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='building.buildingpart', verbose_name='Элемент постройки'),
        ),
    ]
