# Generated by Django 5.0 on 2024-02-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0005_artefact_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefact',
            name='creator',
        ),
    ]
