# Generated by Django 5.0 on 2024-05-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0005_delete_archsitefoto'),
        ('artefact', '0006_artefact_building_artefact_building_part'),
        ('helpers', '0007_alter_element_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arch_site.archaeologicalsite', verbose_name='Памятник'),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpers.storage', verbose_name='Место хранения'),
        ),
    ]
