# Generated by Django 5.0 on 2024-02-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0007_artefact_creator_artefact_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefact',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='artefact',
            name='editor',
        ),
    ]
