# Generated by Django 5.0 on 2024-02-02 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0010_alter_artefact_creator_alter_artefact_editor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='editor+', to=settings.AUTH_USER_MODEL),
        ),
    ]
