# Generated by Django 5.0 on 2024-03-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0002_archaeologicalsite_preservation'),
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaschromatographymassspectrometry',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='arch_site.archaeologicalsite', verbose_name='Памятник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infraredramanmicroscopy',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='arch_site.archaeologicalsite', verbose_name='Памятник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfa',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='arch_site.archaeologicalsite', verbose_name='Памятник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roentgen',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='arch_site.archaeologicalsite', verbose_name='Памятник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scanningelectronmicroscopy',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='arch_site.archaeologicalsite', verbose_name='Памятник'),
            preserve_default=False,
        ),
    ]
