# Generated by Django 5.0 on 2024-01-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rfa',
            options={'verbose_name': 'РФА', 'verbose_name_plural': 'РФА'},
        ),
        migrations.AddField(
            model_name='rfa',
            name='elements',
            field=models.CharField(max_length=255, null=True, verbose_name='Элементы'),
        ),
    ]
