# Generated by Django 5.0 on 2024-04-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_delete_indextable'),
        ('measurement', '0004_remove_petrography_name_petrography_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrography',
            name='color',
            field=models.ManyToManyField(to='helpers.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='petrography',
            name='filler_contains',
            field=models.ManyToManyField(to='helpers.filler', verbose_name='Заполнитель состав'),
        ),
    ]
