# Generated by Django 5.0 on 2024-01-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_remove_scanningelectronmicroscopy_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infraredramanmicroscopy',
            options={'verbose_name': 'ИК и рамановская спектроскопия', 'verbose_name_plural': 'ИК и рамановская спектроскопия'},
        ),
        migrations.AlterModelOptions(
            name='roentgen',
            options={'verbose_name': 'Рентгенофазовый и рентгеноструктурный анализ', 'verbose_name_plural': 'Рентгенофазовый и рентгеноструктурный анализы'},
        ),
        migrations.AlterModelOptions(
            name='scanningelectronmicroscopy',
            options={'verbose_name': 'Растровая электронная микроскопия', 'verbose_name_plural': 'Растровая электронная микроскопия'},
        ),
    ]
