# Generated by Django 5.0 on 2024-04-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_delete_indextable'),
        ('measurement', '0005_alter_petrography_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaschromatographymassspectrometry',
            name='additional_elements',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дополнительные выявленные соединения'),
        ),
        migrations.AlterField(
            model_name='gaschromatographymassspectrometry',
            name='color',
            field=models.ManyToManyField(blank=True, to='helpers.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='gaschromatographymassspectrometry',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='gaschromatographymassspectrometry',
            name='material',
            field=models.CharField(choices=[('CL', 'красочный слой'), ('P', 'штукатурка'), ('C', 'раствор')], max_length=100, verbose_name='Тип вещества'),
        ),
        migrations.AlterField(
            model_name='gaschromatographymassspectrometry',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gaschromatographymassspectrometry',
            name='pigment',
            field=models.ManyToManyField(blank=True, to='helpers.pigment', verbose_name='Пигменты'),
        ),
        migrations.AlterField(
            model_name='gaschromatographymassspectrometry',
            name='source',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Источник референсных значений'),
        ),
        migrations.AlterField(
            model_name='infraredramanmicroscopy',
            name='additional_elements',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дополнительные выявленные соединения'),
        ),
        migrations.AlterField(
            model_name='infraredramanmicroscopy',
            name='color',
            field=models.ManyToManyField(blank=True, to='helpers.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='infraredramanmicroscopy',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='infraredramanmicroscopy',
            name='groups',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Функциональные группы и соединения'),
        ),
        migrations.AlterField(
            model_name='infraredramanmicroscopy',
            name='material',
            field=models.CharField(choices=[('CL', 'красочный слой'), ('P', 'штукатурка'), ('C', 'раствор')], max_length=100, verbose_name='Тип вещества'),
        ),
        migrations.AlterField(
            model_name='infraredramanmicroscopy',
            name='method',
            field=models.CharField(blank=True, choices=[('IR', 'ИК спектроскопия'), ('RS', 'рамановская спектроскопия')], max_length=255, null=True, verbose_name='Метод'),
        ),
        migrations.AlterField(
            model_name='infraredramanmicroscopy',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='infraredramanmicroscopy',
            name='pigment',
            field=models.ManyToManyField(blank=True, to='helpers.pigment', verbose_name='Пигменты'),
        ),
        migrations.AlterField(
            model_name='infraredramanmicroscopy',
            name='source',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Источник референсных значений'),
        ),
        migrations.AlterField(
            model_name='petrography',
            name='color',
            field=models.ManyToManyField(blank=True, to='helpers.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='petrography',
            name='filler_contains',
            field=models.ManyToManyField(blank=True, to='helpers.filler', verbose_name='Заполнитель состав'),
        ),
        migrations.AlterField(
            model_name='rfa',
            name='additional_elements',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дополнительные выявленные соединения'),
        ),
        migrations.AlterField(
            model_name='rfa',
            name='color',
            field=models.ManyToManyField(blank=True, to='helpers.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='rfa',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='rfa',
            name='elements',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Элементы'),
        ),
        migrations.AlterField(
            model_name='rfa',
            name='material',
            field=models.CharField(choices=[('CL', 'красочный слой'), ('P', 'штукатурка'), ('C', 'раствор')], max_length=100, verbose_name='Тип вещества'),
        ),
        migrations.AlterField(
            model_name='rfa',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rfa',
            name='pigment',
            field=models.ManyToManyField(blank=True, to='helpers.pigment', verbose_name='Пигменты'),
        ),
        migrations.AlterField(
            model_name='rfa',
            name='source',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Источник референсных значений'),
        ),
        migrations.AlterField(
            model_name='roentgen',
            name='additional_elements',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дополнительные выявленные соединения'),
        ),
        migrations.AlterField(
            model_name='roentgen',
            name='color',
            field=models.ManyToManyField(blank=True, to='helpers.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='roentgen',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='roentgen',
            name='material',
            field=models.CharField(choices=[('CL', 'красочный слой'), ('P', 'штукатурка'), ('C', 'раствор')], max_length=100, verbose_name='Тип вещества'),
        ),
        migrations.AlterField(
            model_name='roentgen',
            name='mineral',
            field=models.ManyToManyField(blank=True, to='helpers.mineral', verbose_name='Минералы'),
        ),
        migrations.AlterField(
            model_name='roentgen',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roentgen',
            name='pigment',
            field=models.ManyToManyField(blank=True, to='helpers.pigment', verbose_name='Пигменты'),
        ),
        migrations.AlterField(
            model_name='roentgen',
            name='source',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Источник референсных значений'),
        ),
        migrations.AlterField(
            model_name='scanningelectronmicroscopy',
            name='additional_elements',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Дополнительные выявленные соединения'),
        ),
        migrations.AlterField(
            model_name='scanningelectronmicroscopy',
            name='color',
            field=models.ManyToManyField(blank=True, to='helpers.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='scanningelectronmicroscopy',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='scanningelectronmicroscopy',
            name='elements',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Элементы'),
        ),
        migrations.AlterField(
            model_name='scanningelectronmicroscopy',
            name='material',
            field=models.CharField(choices=[('CL', 'красочный слой'), ('P', 'штукатурка'), ('C', 'раствор')], max_length=100, verbose_name='Тип вещества'),
        ),
        migrations.AlterField(
            model_name='scanningelectronmicroscopy',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='scanningelectronmicroscopy',
            name='pigment',
            field=models.ManyToManyField(blank=True, to='helpers.pigment', verbose_name='Пигменты'),
        ),
        migrations.AlterField(
            model_name='scanningelectronmicroscopy',
            name='source',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Источник референсных значений'),
        ),
    ]
