# Generated by Django 5.0 on 2024-04-08 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0004_alter_artefact_name'),
        ('artwork', '0010_alter_frescoe_code_alter_indoorartwork_code'),
        ('measurement', '0006_alter_gaschromatographymassspectrometry_additional_elements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaschromatographymassspectrometry',
            name='artefact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact'),
        ),
        migrations.AddField(
            model_name='gaschromatographymassspectrometry',
            name='frescoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.frescoe'),
        ),
        migrations.AddField(
            model_name='gaschromatographymassspectrometry',
            name='indoor_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.indoorartwork'),
        ),
        migrations.AddField(
            model_name='infraredramanmicroscopy',
            name='artefact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact'),
        ),
        migrations.AddField(
            model_name='infraredramanmicroscopy',
            name='frescoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.frescoe'),
        ),
        migrations.AddField(
            model_name='infraredramanmicroscopy',
            name='indoor_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.indoorartwork'),
        ),
        migrations.AddField(
            model_name='rfa',
            name='artefact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact'),
        ),
        migrations.AddField(
            model_name='rfa',
            name='frescoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.frescoe'),
        ),
        migrations.AddField(
            model_name='rfa',
            name='indoor_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.indoorartwork'),
        ),
        migrations.AddField(
            model_name='roentgen',
            name='artefact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact'),
        ),
        migrations.AddField(
            model_name='roentgen',
            name='frescoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.frescoe'),
        ),
        migrations.AddField(
            model_name='roentgen',
            name='indoor_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.indoorartwork'),
        ),
        migrations.AddField(
            model_name='scanningelectronmicroscopy',
            name='artefact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact'),
        ),
        migrations.AddField(
            model_name='scanningelectronmicroscopy',
            name='frescoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.frescoe'),
        ),
        migrations.AddField(
            model_name='scanningelectronmicroscopy',
            name='indoor_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.indoorartwork'),
        ),
    ]
