# Generated by Django 5.0 on 2024-04-08 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0004_alter_artefact_name'),
        ('artwork', '0010_alter_frescoe_code_alter_indoorartwork_code'),
        ('measurement', '0007_gaschromatographymassspectrometry_artefact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petrography',
            name='artefact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact'),
        ),
        migrations.AddField(
            model_name='petrography',
            name='frescoe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.frescoe'),
        ),
        migrations.AddField(
            model_name='petrography',
            name='indoor_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.indoorartwork'),
        ),
    ]
