# Generated by Django 5.0 on 2024-01-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0015_filler'),
        ('measurement', '0007_remove_gaschromatographymassspectrometry_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petrography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('measurement_date', models.DateField(verbose_name='Дата исследования')),
                ('number', models.CharField(max_length=255, verbose_name='Номер шлифа')),
                ('operator', models.CharField(max_length=255, verbose_name='Оператор')),
                ('equipment', models.CharField(max_length=255, verbose_name='Оборудование')),
                ('binder_name', models.CharField(max_length=255, null=True, verbose_name='Вяжущее название')),
                ('binder_percent', models.IntegerField(blank=True, null=True, verbose_name='Вяжущее %')),
                ('binder_description', models.TextField(null=True, verbose_name='Вяжущее описание')),
                ('filler_percent', models.IntegerField(blank=True, null=True, verbose_name='Заполнитель %')),
                ('filler_description', models.TextField(null=True, verbose_name='Заполнитель описание')),
                ('pores', models.CharField(blank=True, choices=[('N', 'Пор нет'), ('SM', 'Поры мелкие'), ('LG', 'Поры крупные')], max_length=100, null=True, verbose_name='Наличие пор')),
                ('pores_diameter', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='Диаметр пор')),
                ('filler_contains', models.ManyToManyField(to='helpers.filler', verbose_name='Заполнитель состав')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
