# Generated by Django 5.0 on 2024-04-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0004_element'),
        ('measurement', '0009_alter_gaschromatographymassspectrometry_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanningelectronmicroscopy',
            name='elements',
        ),
        migrations.AddField(
            model_name='scanningelectronmicroscopy',
            name='elements',
            field=models.ManyToManyField(blank=True, to='helpers.element', verbose_name='Элементы периодической таблицы'),
        ),
    ]
