# Generated by Django 5.0 on 2024-04-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0011_petrography_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanningelectronmicroscopy',
            old_name='elements',
            new_name='element',
        ),
    ]
