# Generated by Django 5.0 on 2024-02-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0013_gaschromatographymassspectrometry_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaschromatographymassspectrometry',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='gaschromatographymassspectrometry',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='infraredramanmicroscopy',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='infraredramanmicroscopy',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='petrography',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='petrography',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='rfa',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='rfa',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='roentgen',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='roentgen',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='scanningelectronmicroscopy',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='scanningelectronmicroscopy',
            name='editor',
        ),
    ]
