# Generated by Django 5.0 on 2024-02-01 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0014_remove_gaschromatographymassspectrometry_creator_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gaschromatographymassspectrometry',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='creator_core.models.slug_mixin+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gaschromatographymassspectrometry',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='editor_core.models.slug_mixin+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infraredramanmicroscopy',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='creator_core.models.slug_mixin+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infraredramanmicroscopy',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='editor_core.models.slug_mixin+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petrography',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='creator_core.models.slug_mixin+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petrography',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='editor_core.models.slug_mixin+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfa',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='creator_core.models.slug_mixin+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rfa',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='editor_core.models.slug_mixin+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roentgen',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='creator_core.models.slug_mixin+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roentgen',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='editor_core.models.slug_mixin+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanningelectronmicroscopy',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='creator_core.models.slug_mixin+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scanningelectronmicroscopy',
            name='editor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='editor_core.models.slug_mixin+', to=settings.AUTH_USER_MODEL),
        ),
    ]
