# Generated by Django 5.0 on 2024-05-04 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0006_artefact_building_artefact_building_part'),
        ('measurement', '0014_alter_gaschromatographymassspectrometry_artefact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaschromatographymassspectrometry',
            name='artefact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact'),
        ),
        migrations.AlterField(
            model_name='infraredramanmicroscopy',
            name='artefact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact'),
        ),
        migrations.AlterField(
            model_name='rfa',
            name='artefact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact'),
        ),
        migrations.AlterField(
            model_name='roentgen',
            name='artefact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact'),
        ),
        migrations.AlterField(
            model_name='scanningelectronmicroscopy',
            name='artefact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact'),
        ),
    ]
