# Generated by Django 5.0 on 2024-02-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0017_alter_gaschromatographymassspectrometry_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gaschromatographymassspectrometry',
            options={'verbose_name': 'Газовая хроматография и масс-спектрометрия', 'verbose_name_plural': 'Газовая хроматография и масс-спектрометрия'},
        ),
        migrations.AlterField(
            model_name='gaschromatographymassspectrometry',
            name='material',
            field=models.CharField(choices=[('CL', 'красочный слой'), ('P', 'штукатурка'), ('C', 'раствор')], max_length=100, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='infraredramanmicroscopy',
            name='material',
            field=models.CharField(choices=[('CL', 'красочный слой'), ('P', 'штукатурка'), ('C', 'раствор')], max_length=100, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='rfa',
            name='material',
            field=models.CharField(choices=[('CL', 'красочный слой'), ('P', 'штукатурка'), ('C', 'раствор')], max_length=100, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='roentgen',
            name='material',
            field=models.CharField(choices=[('CL', 'красочный слой'), ('P', 'штукатурка'), ('C', 'раствор')], max_length=100, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='scanningelectronmicroscopy',
            name='material',
            field=models.CharField(choices=[('CL', 'красочный слой'), ('P', 'штукатурка'), ('C', 'раствор')], max_length=100, verbose_name='Материал'),
        ),
    ]
