# Generated by Django 5.0 on 2024-03-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arch_site', '0001_initial'),
        ('artefact', '0001_initial'),
        ('artwork', '0001_initial'),
        ('building', '0001_initial'),
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип файла',
                'verbose_name_plural': 'Типы файлов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('filename', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('object_storage_key', models.CharField(max_length=255)),
                ('artefact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact')),
                ('bulding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.building')),
                ('bulding_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.buildingpart')),
                ('frescoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.frescoe')),
                ('gc_ms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.gaschromatographymassspectrometry')),
                ('indoor_artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.indoorartwork')),
                ('infrared_ramanov', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.infraredramanmicroscopy')),
                ('lotok', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.lotok')),
                ('petrography', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.petrography')),
                ('rfa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.rfa')),
                ('roentgen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.roentgen')),
                ('scanning_microscopy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.scanningelectronmicroscopy')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arch_site.archaeologicalsite')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='file.filetype')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ('type',),
            },
        ),
    ]
