# Generated by Django 4.2.7 on 2023-12-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('filename', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('F', 'фотография'), ('PIC', 'рисунок'), ('P', 'план')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
