# Generated by Django 5.0 on 2024-03-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='lotok',
        ),
    ]
