# Generated by Django 4.2.7 on 2023-12-12 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0020_remove_building_file_building_site'),
        ('arch_site', '0005_alter_archaeologicalsite_slug'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='bulding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.building'),
        ),
        migrations.AddField(
            model_name='file',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arch_site.archaeologicalsite'),
        ),
    ]
