# Generated by Django 4.2.7 on 2023-12-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_file_bulding_file_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='object_storage_key',
            field=models.CharField(default=str, max_length=255),
            preserve_default=False,
        ),
    ]
