# Generated by Django 5.0 on 2024-04-15 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0005_delete_archsitefoto'),
        ('artefact', '0005_alter_artefact_options'),
        ('artwork', '0012_frescoe_building_part_indoorartwork_building_part'),
        ('building', '0003_alter_building_options'),
        ('file', '0003_foto'),
        ('measurement', '0010_remove_scanningelectronmicroscopy_elements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('id',), 'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='type',
        ),
        migrations.AddField(
            model_name='foto',
            name='artefact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact'),
        ),
        migrations.AddField(
            model_name='foto',
            name='bulding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.building'),
        ),
        migrations.AddField(
            model_name='foto',
            name='bulding_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.buildingpart'),
        ),
        migrations.AddField(
            model_name='foto',
            name='frescoe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.frescoe'),
        ),
        migrations.AddField(
            model_name='foto',
            name='gc_ms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.gaschromatographymassspectrometry'),
        ),
        migrations.AddField(
            model_name='foto',
            name='indoor_artwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.indoorartwork'),
        ),
        migrations.AddField(
            model_name='foto',
            name='infrared_ramanov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.infraredramanmicroscopy'),
        ),
        migrations.AddField(
            model_name='foto',
            name='petrography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.petrography'),
        ),
        migrations.AddField(
            model_name='foto',
            name='rfa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.rfa'),
        ),
        migrations.AddField(
            model_name='foto',
            name='roentgen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.roentgen'),
        ),
        migrations.AddField(
            model_name='foto',
            name='scanning_microscopy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.scanningelectronmicroscopy'),
        ),
        migrations.AddField(
            model_name='foto',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arch_site.archaeologicalsite'),
        ),
    ]
