# Generated by Django 5.0 on 2023-12-22 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0021_alter_building_comment_alter_building_year_max_and_more'),
        ('file', '0007_alter_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='bulding_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='building.buildingpart'),
        ),
    ]
