# Generated by Django 5.0 on 2023-12-23 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_remove_artwork_preservation_id_artwork_building_and_more'),
        ('file', '0008_file_bulding_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='artwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.artwork'),
        ),
    ]
