# Generated by Django 5.0 on 2023-12-24 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0009_rename_artwork_indoorartwork_lotok'),
        ('file', '0009_file_artwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='artwork',
            new_name='indoor_artwork',
        ),
        migrations.AddField(
            model_name='file',
            name='lotok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.lotok'),
        ),
    ]
