# Generated by Django 5.0 on 2023-12-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0010_frescoe'),
        ('file', '0010_rename_artwork_file_indoor_artwork_file_lotok'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='frescoe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artwork.frescoe'),
        ),
    ]
