# Generated by Django 5.0 on 2024-01-05 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefact', '0001_initial'),
        ('file', '0011_file_frescoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='artefact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artefact.artefact'),
        ),
    ]
