# Generated by Django 5.0 on 2024-01-05 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0012_file_artefact'),
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='rfa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.rfa'),
        ),
    ]
