# Generated by Django 5.0 on 2024-01-06 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0013_file_rfa'),
        ('measurement', '0003_alter_rfa_material_scanningelectronmicroscopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='scanning_microscopy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.scanningelectronmicroscopy'),
        ),
    ]
