# Generated by Django 5.0 on 2024-01-06 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0014_file_scanning_microscopy'),
        ('measurement', '0004_remove_scanningelectronmicroscopy_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='gc_ms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.gaschromatographymassspectrometry'),
        ),
        migrations.AddField(
            model_name='file',
            name='infrared_ramanov',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.infraredramanmicroscopy'),
        ),
        migrations.AddField(
            model_name='file',
            name='roentgen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.roentgen'),
        ),
    ]
