# Generated by Django 5.0 on 2024-01-23 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0016_alter_file_options_alter_filetype_options'),
        ('measurement', '0008_petrography'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='petrography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='measurement.petrography'),
        ),
    ]
