# Generated by Django 5.0 on 2024-03-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frescoe',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='find_date_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год находки от:'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='find_date_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='square_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер квадрата/участка/пласта по археологическим отчетам'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='find_date_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год находки от:'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='find_date_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='square_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер квадрата/участка/пласта по археологическим отчетам'),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='find_date_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год находки от:'),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='find_date_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='square_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер квадрата/участка/пласта по археологическим отчетам'),
        ),
    ]
