# Generated by Django 4.2.7 on 2023-12-01 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_alter_artwork_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
