# Generated by Django 4.2.7 on 2023-11-15 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_artwork_created_at_artwork_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='preservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
