# Generated by Django 5.0 on 2024-03-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_alter_frescoe_comment_alter_frescoe_find_date_from_and_more'),
        ('file', '0002_remove_file_lotok'),
    ]

    operations = [
        migrations.AddField(
            model_name='frescoe',
            name='kind',
            field=models.CharField(default='фреска', max_length=255, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='code',
            field=models.CharField(max_length=100, null=True, verbose_name='Шифр'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='comment',
            field=models.TextField(null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='find_date_from',
            field=models.IntegerField(null=True, verbose_name='Год находки от:'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='find_date_to',
            field=models.IntegerField(null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='square_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер квадрата/участка/пласта по археологическим отчетам'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='code',
            field=models.CharField(max_length=100, null=True, verbose_name='Шифр'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='comment',
            field=models.TextField(null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='find_date_from',
            field=models.IntegerField(null=True, verbose_name='Год находки от:'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='find_date_to',
            field=models.IntegerField(null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='square_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер квадрата/участка/пласта по археологическим отчетам'),
        ),
        migrations.DeleteModel(
            name='Lotok',
        ),
    ]
