# Generated by Django 5.0 on 2024-03-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_frescoe_kind_alter_frescoe_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frescoe',
            name='kind',
            field=models.CharField(choices=[('L', 'лоток'), ('I', 'индивидуальная фреска')], default='I', max_length=255, verbose_name='Вид'),
        ),
    ]
