# Generated by Django 5.0 on 2023-12-23 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_alter_artwork_description'),
        ('building', '0023_remove_buildingpart_building'),
        ('helpers', '0011_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='preservation_id',
        ),
        migrations.AddField(
            model_name='artwork',
            name='building',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='building.building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='building_part',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='building.buildingpart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='color',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='helpers.color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='preservation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='helpers.preservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='size',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='year_max',
            field=models.IntegerField(default=2, verbose_name='До'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='year_min',
            field=models.IntegerField(default=2, verbose_name='От'),
            preserve_default=False,
        ),
    ]
