# Generated by Django 5.0 on 2024-03-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_alter_frescoe_code_alter_indoorartwork_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frescoe',
            name='code',
            field=models.IntegerField(null=True, verbose_name='Шифр'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='code',
            field=models.IntegerField(null=True, verbose_name='Шифр'),
        ),
    ]
