# Generated by Django 5.0 on 2023-12-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_remove_artwork_preservation_id_artwork_building_and_more'),
        ('helpers', '0011_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='color',
        ),
        migrations.AddField(
            model_name='artwork',
            name='color',
            field=models.ManyToManyField(to='helpers.color'),
        ),
    ]
