# Generated by Django 5.0 on 2024-03-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_alter_frescoe_code_alter_indoorartwork_code'),
        ('helpers', '0002_indextable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indoorartwork',
            name='square_number',
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество фрагментов'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='code',
            field=models.IntegerField(db_index=True, null=True, unique=True, verbose_name='Шифр'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='helpers.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='find_date_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год находки от:'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='find_date_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='square_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер квадрата/участка/пласта по археологическим отчетам'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='code',
            field=models.IntegerField(db_index=True, null=True, unique=True, verbose_name='Шифр'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='color',
            field=models.ManyToManyField(blank=True, null=True, to='helpers.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='find_date_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год находки от:'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='find_date_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
