# Generated by Django 5.0 on 2023-12-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_remove_artwork_color_artwork_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
