# Generated by Django 5.0 on 2023-12-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0007_artwork_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='slug',
        ),
    ]
