# Generated by Django 5.0 on 2024-03-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0007_remove_indoorartwork_square_number_and_more'),
        ('helpers', '0002_indextable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frescoe',
            name='color',
            field=models.ManyToManyField(blank=True, to='helpers.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='color',
            field=models.ManyToManyField(blank=True, to='helpers.color', verbose_name='Цвета'),
        ),
    ]
