# Generated by Django 5.0 on 2024-04-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0008_alter_frescoe_color_alter_indoorartwork_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frescoe',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер'),
        ),
    ]
