# Generated by Django 5.0 on 2024-04-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0009_alter_frescoe_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frescoe',
            name='code',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Шифр'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='code',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Шифр'),
        ),
    ]
