# Generated by Django 5.0 on 2023-12-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0009_rename_artwork_indoorartwork_lotok'),
        ('building', '0023_remove_buildingpart_building'),
        ('helpers', '0012_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frescoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=255)),
                ('year_min', models.IntegerField(verbose_name='От')),
                ('year_max', models.IntegerField(verbose_name='До')),
                ('find_date', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
                ('comment', models.TextField(null=True)),
                ('square_number', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('M', 'массовый'), ('I', 'индивидуальный')], max_length=100)),
                ('museum_code', models.CharField(max_length=255)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='building.building')),
                ('building_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='building.buildingpart')),
                ('color', models.ManyToManyField(to='helpers.color')),
                ('lotok', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='artwork.lotok')),
                ('preservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpers.preservation')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpers.storage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
