# Generated by Django 5.0 on 2023-12-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0010_frescoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='indoorartwork',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
