# Generated by Django 5.0 on 2023-12-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0011_indoorartwork_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotok',
            old_name='find_date',
            new_name='find_date_from',
        ),
        migrations.AddField(
            model_name='frescoe',
            name='slug',
            field=models.SlugField(default='dads'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indoorartwork',
            name='slug',
            field=models.SlugField(default='dsadasdsad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotok',
            name='find_date_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lotok',
            name='slug',
            field=models.SlugField(default='asdasdas'),
            preserve_default=False,
        ),
    ]
