# Generated by Django 5.0 on 2023-12-25 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0012_rename_find_date_lotok_find_date_from_frescoe_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frescoe',
            old_name='find_date',
            new_name='find_date_from',
        ),
        migrations.RenameField(
            model_name='lotok',
            old_name='name',
            new_name='museum_code',
        ),
        migrations.RemoveField(
            model_name='frescoe',
            name='lotok',
        ),
        migrations.RemoveField(
            model_name='indoorartwork',
            name='size',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='building',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='building_part',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='code',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='color',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='find_date_from',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='find_date_to',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='preservation',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='square_number',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='year_max',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='year_min',
        ),
        migrations.AddField(
            model_name='frescoe',
            name='find_date_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='frescoe',
            name='indoor_artwork',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='artwork.indoorartwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indoorartwork',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indoorartwork',
            name='find_date_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='indoorartwork',
            name='find_date_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='indoorartwork',
            name='square_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lotok',
            name='indoor_artwork',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='artwork.indoorartwork'),
            preserve_default=False,
        ),
    ]
