# Generated by Django 5.0 on 2024-04-18 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0012_frescoe_building_part_indoorartwork_building_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frescoe',
            name='indoor_artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='artwork.indoorartwork', verbose_name='Изображение в постройке'),
        ),
    ]
