# Generated by Django 5.0 on 2023-12-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0013_rename_find_date_frescoe_find_date_from_and_more'),
        ('building', '0023_remove_buildingpart_building'),
        ('helpers', '0012_storage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indoorartwork',
            options={'verbose_name': 'Изображение в постройке', 'verbose_name_plural': 'Изображения в постройке'},
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='building.building', verbose_name='Постройка'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='building_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='building.buildingpart', verbose_name='Элемент постройки'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Шифр'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='color',
            field=models.ManyToManyField(to='helpers.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='comment',
            field=models.TextField(null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='find_date_from',
            field=models.IntegerField(null=True, verbose_name='Год находки от:'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='find_date_to',
            field=models.IntegerField(null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='preservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpers.preservation', verbose_name='Сохранность'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='square_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер квадрата/участка/пласта по археологическим отчетам'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='year_max',
            field=models.IntegerField(verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='year_min',
            field=models.IntegerField(verbose_name='Датировка от:'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='building.building', verbose_name='Постройка'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='building_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='building.buildingpart', verbose_name='Элемент постройки'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Шифр'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='color',
            field=models.ManyToManyField(to='helpers.color', verbose_name='Цвета'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='comment',
            field=models.TextField(null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='find_date_from',
            field=models.IntegerField(null=True, verbose_name='Год находки от:'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='find_date_to',
            field=models.IntegerField(null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='preservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpers.preservation', verbose_name='Сохранность'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='square_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер квадрата/участка/пласта по археологическим отчетам'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='year_max',
            field=models.IntegerField(verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='year_min',
            field=models.IntegerField(verbose_name='Датировка от:'),
        ),
    ]
