# Generated by Django 5.0 on 2023-12-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0014_alter_indoorartwork_options_alter_frescoe_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frescoe',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
