# Generated by Django 5.0 on 2023-12-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0015_alter_frescoe_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frescoe',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
