# Generated by Django 5.0 on 2024-04-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0015_alter_frescoe_building_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frescoe',
            name='square_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер квадрата/участка/пласта по                       археологическим отчетам'),
        ),
    ]
