# Generated by Django 5.0 on 2024-01-11 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0016_alter_frescoe_slug_alter_indoorartwork_slug_and_more'),
        ('building', '0027_alter_building_slug'),
        ('helpers', '0014_mineral'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotok',
            name='building',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='building.building', verbose_name='Постройка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotok',
            name='building_part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='building.buildingpart', verbose_name='Элемент постройки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotok',
            name='code',
            field=models.CharField(default=1, max_length=100, verbose_name='Шифр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotok',
            name='color',
            field=models.ManyToManyField(to='helpers.color', verbose_name='Цвета'),
        ),
        migrations.AddField(
            model_name='lotok',
            name='comment',
            field=models.TextField(null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='lotok',
            name='find_date_from',
            field=models.IntegerField(null=True, verbose_name='Год находки от:'),
        ),
        migrations.AddField(
            model_name='lotok',
            name='find_date_to',
            field=models.IntegerField(null=True, verbose_name='до:'),
        ),
        migrations.AddField(
            model_name='lotok',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotok',
            name='preservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='helpers.preservation', verbose_name='Сохранность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotok',
            name='square_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Номер квадрата/участка/пласта по археологическим отчетам'),
        ),
        migrations.AddField(
            model_name='lotok',
            name='year_max',
            field=models.IntegerField(default=1, verbose_name='до:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotok',
            name='year_min',
            field=models.IntegerField(default=1, verbose_name='Датировка от:'),
            preserve_default=False,
        ),
    ]
