# Generated by Django 5.0 on 2024-04-30 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0016_alter_frescoe_square_number'),
        ('helpers', '0007_alter_element_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frescoe',
            name='museum_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Музейный шифр'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='preservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helpers.preservation', verbose_name='Сохранность'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='preservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='helpers.preservation', verbose_name='Сохранность'),
        ),
    ]
