# Generated by Django 5.0 on 2024-01-18 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arch_site', '0014_alter_archaeologicalsite_options'),
        ('artwork', '0017_lotok_building_lotok_building_part_lotok_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frescoe',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arch_site.archaeologicalsite', verbose_name='Памятник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indoorartwork',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arch_site.archaeologicalsite', verbose_name='Памятник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lotok',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='arch_site.archaeologicalsite', verbose_name='Памятник'),
            preserve_default=False,
        ),
    ]
