# Generated by Django 5.0 on 2024-01-31 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0018_frescoe_site_indoorartwork_site_lotok_site'),
        ('helpers', '0016_alter_color_options_alter_filler_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frescoe',
            options={'verbose_name': 'Фреска', 'verbose_name_plural': 'Фрески'},
        ),
        migrations.AlterModelOptions(
            name='lotok',
            options={'verbose_name': 'Лоток', 'verbose_name_plural': 'Лотки'},
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Количество фрагментов'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='indoor_artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artwork.indoorartwork', verbose_name='Изображение в постройке'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='museum_code',
            field=models.CharField(max_length=255, verbose_name='Музейный шифр'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='size',
            field=models.CharField(max_length=255, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpers.storage', verbose_name='Место хранения'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='type',
            field=models.CharField(choices=[('M', 'массовый'), ('I', 'индивидуальный')], max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Количество фрагментов'),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='indoor_artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artwork.indoorartwork', verbose_name='Изображение в постройке'),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='museum_code',
            field=models.CharField(max_length=255, verbose_name='Музейный шифр'),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='size',
            field=models.CharField(max_length=255, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helpers.storage', verbose_name='Место хранения'),
        ),
    ]
