# Generated by Django 5.0 on 2024-02-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0020_frescoe_creator_indoorartwork_creator_lotok_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frescoe',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='indoorartwork',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='creator',
        ),
    ]
