# Generated by Django 5.0 on 2024-02-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0022_frescoe_creator_frescoe_editor_indoorartwork_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frescoe',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='frescoe',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='indoorartwork',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='indoorartwork',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='lotok',
            name='editor',
        ),
    ]
