# Generated by Django 5.0 on 2024-02-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0026_alter_frescoe_creator_alter_frescoe_editor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotok',
            name='type',
            field=models.CharField(choices=[('M', 'массовый'), ('I', 'индивидуальный')], default='M', max_length=100, verbose_name='Тип'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='year_max',
            field=models.IntegerField(blank=True, help_text='Даты до н.э. должны быть отрицательными', null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='frescoe',
            name='year_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Датировка от:'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='year_max',
            field=models.IntegerField(blank=True, help_text='Даты до н.э. должны быть отрицательными', null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='indoorartwork',
            name='year_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Датировка от:'),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='year_max',
            field=models.IntegerField(blank=True, help_text='Даты до н.э. должны быть отрицательными', null=True, verbose_name='до:'),
        ),
        migrations.AlterField(
            model_name='lotok',
            name='year_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Датировка от:'),
        ),
    ]
